# Dataset settings
data_root: cityscapes
copy_paste: true
jitter_mode: large
batch_size: 8
fraction: 0.5
fraction_seed: 14

# Model Settings
backbone: resnet50_fpn
min_size: 1024
max_size: 2048
pretrained: true
pretrained_backbone: false

# Training settings
epochs: 66
checkpoint: null
eval_interval: 5
log_interval: 50

# Optimizer settings
lr: 0.01
momentum: 0.9
weight_decay: 0.0001
step_size: 48
gamma: 0.1
